module GithubOrgNames
  GITHUB_MAP = {
              'BTC' => 'bitcoin', 'ETH' => 'ethereum', 'BCH' => 'Bitcoin-ABC',
              'XRP' => 'ripple', 'LTC' => 'litecoin-project', 'DASH' => 'dashpay',
              'XEM' => 'NemProject', 'MIOTA' => 'iotaledger',
              'XMR' => 'monero-project', 'NEO' => 'neo-project',
              'ETC' => 'ethereumproject', 'QTUM' => 'qtumproject',
              'HSR' => 'HcashOrg', 'OMG' => 'omise', 'BCC' => 'bitconnectcoin',
              'LSK' => 'LiskHQ', 'STRAT' => 'stratisproject', 'ZEC' => 'zcash',
              'WAVES' => 'WAVESPLATFORM', 'PAY' => 'tenx-tech', 'EOS' => 'EOSIO',
              'BTS' => 'bitshares', 'STEEM' => 'steemit', 'BCN' => 'amjuarez',
              'USDT' => 'N/A', 'MAID' => 'maidsafe',
              'REP' => 'AugurProject', 'FCT' => 'FactomProject',
              'ARK' => 'ArkEcosystem', 'GNT' => 'golemfactory',
              'BAT' => 'brave-intl', 'XLM' => 'stellar',
              'SC' => 'NebulousLabs', 'MCO' => 'N/A', 'GBYTE' => 'byteball',
              'VERI' => 'veritaseum', 'DCR' => 'decred',
              'DOGE' => 'dogecoin' , 'BNB' => 'N/A', 'ICN' => 'N/A',
              'GNO' => 'gnosis', 'DGD' => 'DigixGlobal', 'MTL' => 'MetalPay',
              'CVC' => 'N/A', 'ZRX' => '0xProject', 'SNT' => 'status-im',
              'GAS' => 'neo-project',
              'KMD' => 'jl777', 'PPT' => 'bitpopulous',
              'PIVX' => 'PIVX-Project', 'GAME' => 'gamecredits-project',
              'ARDR' => 'N/A', 'DGB' => 'digibyte',
              'MCAP' => 'BitcoingGrowthFund',
              'BNT' => 'bancorprotocol', 'NXS' => 'Nexusoft', 'BTM' => 'bytom',
              'BLOCK' => 'BlocknetDX', 'NXT' => 'mrv777', 'FUN' => 'N/A',
              'ANT' => 'aragon', 'UBQ' => 'ubiq', 'STORJ' => 'storj',
              'LKK' => 'LykkeCity', 'NLC2' => 'NoLimitCoin',
              'MGO' => 'N/A', 'CFI' => 'cofoundit', 'ICO' => 'N/A',
              'BTCD' => 'laowais', 'SYS' => 'syscoin',
              'SNGLS' => 'SingularDTV', 'ETP' => 'mvs-org', 'TNT' => 'tierion',
              'PART' => 'particl', 'DNT' => 'district0x',
              'TKN' => 'MonolithDAO', 'ADX' => 'AdExBlockchain',
              'WINGS' => 'WingsDao', 'DCT' => 'DECENTfoundation',
              'EDG' => 'EdgelessCasino',
              'XAS' => 'AschPlatform', 'PLR' => 'twentythirty', 'BQX' => 'N/A',
              '1ST' => 'firstbloodio', 'STX' => 'stx-technologies',
              'RLC' => 'iExecBlockchainComputing',
              'CDT' => 'CoinDashio', 'EMC' => 'Emercoin',
              'XVG' => 'vergecurrency', 'MLN' => 'melonproject',
              'PPC' => 'peercoin', 'LEO' => 'Leocoin-project',
              'NMR' => 'numerai', 'FRST' => 'firstconn', 'XEL' => 'elastic-coin',
              'ROUND' => 'N/A', 'IOC' => 'IOCoin',
              'XCP' => 'CounterpartyXCP', 'XRL' => 'N/A', 'NLG' => 'Gulden',
              'TAAS' => 'N/A', 'NAV' => 'NAVCoin', 'VSL' => 'jamesgroton',
              'PST' => 'primasio', 'FAIR' => 'faircoin', 'XZC' => 'zcoinofficial',
              'QRL' => 'theQRL', 'RDD' => 'reddcoin-project', 'ADT' => 'AdChain',
              'MSP' => 'mothershipcx', 'NMC' => 'namecoin', 'LUN' => 'lunyr',
              'TCC' => 'N/A', 'VTC' => 'vertcoin', 'VIA' => 'viacoin',
              'CRW' => 'Crowndev', 'EXP' => 'expanse-project', 'POT' => 'potcoin',
              'MYST' => 'MysteriumNetwork', 'SNM' => 'sonm-io',
              'DICE' => 'N/A', 'UNITY' => 'SuperNETorg', 'HMQ' => 'humaniq',
              'ION' => 'ionomy', 'SAN' => 'santiment',
              'MONA' => 'monacoinproject', 'PTOY' => 'Patientory',
              'CLOAK' => 'CloakCoin', 'EB3' => 'eb3developer', 'SAFEX' => 'safex',
              'TRST' => 'WeTrustPlatform', 'IXT' => 'N/A', 'PLBT' => 'N/A',
              'XAUR' => 'XaurumTeam', 'LBC' => 'lbryio',
              'SPR' => 'Spreadcoin', 'SKY' => 'skycoin', 'ZEN' => 'zencashio',
              'OAX' => 'openanx', 'NXC' => 'N/A', 'BLK' => 'CoinBlack',
              'BAY' => 'bitbayteam', 'OMNI' => 'OmniLayer', 'WGR' => 'wagerr',
              'PPY' => 'PBSA', 'SOAR' => 'neowenyuan27',
              'CLAM' => 'nochowderforyou', 'RADS' => 'tm2013', 'DTB' => 'N/A',
              'GUP' => 'matchpool', 'MUE' => 'MUEcoin',
              'GOLOS' => 'GolosChain', 'SHIFT' => 'ShiftNrg',
              'TIME' => 'ChronoBank', 'AGRS' => 'N/A', 'QAU' => 'N/A',
              'MOON' => 'mooncoindev', 'AMP' => 'synereo', 'SLS' => 'saluscoin',
              'XDN' => 'xdn-project', 'SIB' => 'ivansib',
              'XRB' => 'clemahieu', 'RISE' => 'risevision', 'YBC' => 'ybcoin',
              'ECOB' => 'N/A', 'UNO' => 'unobtanium-official',
              'ENRG' => 'EnergyCoin', 'CAT' => 'BlockCatIO', 'GRC' => 'gridcoin',
              'BURST' => 'burst-team', 'NET' => 'nimiq-network',
              'SWT' => 'swarmcity', 'XBY' => 'borzalom', 'BCAP' => 'BCAPtoken',
              'ECN' => 'ecoinclub', 'XSPEC' => 'spectrecoin',
              'RBY' => 'rubycoinorg', 'AEON' => 'aeonix',
              'WCT' => 'WAVESPLATFORM', 'MUSIC' => 'Musicoin',
              'NEOS' => 'neoscoin',
              'TIX' => 'blocktix', 'FLO' => 'florincoin', 'BET' => 'N/A',
              'OBITS' => 'N/A', 'EAC' => 'earthcoinproject',
              'BITCNY' => 'N/A', 'ONION' => 'deeponion', 'EDR' => 'EDRCoin',
              'DMD' => 'DMDcoin', 'VOX' => 'voxel',
              'PLU' => 'PlutusIt', 'INCNT' => 'N/A', 'UNY' => 'N/A',
              'DENT' => 'N/A', 'BCY' => 'everdreamsoft',
              'LMC' => 'lomocoin', 'FTC' => 'FeatherCoin',
              'ECC' => 'Greg-Griffith', 'VRC' => 'vericoin',
              'SPHR' => 'SphereDevs',
              'EMC2' => 'einsteinium', 'GAM' => 'collincrypto',
              'PEPECASH' => 'N/A', 'XPM' => 'primecoin', 'MBRS' => 'TheEmbermine',
              'HEAT' => 'Heat-Ledger-Ltd', 'MYB' => 'MyBitDev',
              'TOA' => 'toacoin', 'EMV' => 'N/A', 'NOTE' => 'DNotesCoin',
              'FLDC' => 'FoldingCoin', 'XBC' => 'BitcoinPlus-org',
              'GRS' => 'Groestlcoin', 'EXCL' => 'N/A', 'QWARK' => 'N/A',
              'TFL' => 'N/A', 'WDC' => 'N/A', 'CRB' => 'N/A', 'IFC' => 'N/A', 'PUT' => 'N/A', 'PINK' => 'N/A',
              'NDC' => 'N/A', 'SLR' => 'N/A', 'SEQ' => 'N/A', 'PZM' => 'N/A', 'APX' => 'N/A', 'TRIG' => 'N/A',
              'PDC' => 'N/A', 'EMB' => 'N/A', 'BASH' => 'N/A', 'PBT' => 'N/A', 'OCT' => 'N/A', 'MGC' => 'N/A',
              'VASH' => 'N/A', 'OK' => 'N/A', 'DBIX' => 'N/A', 'NVC' => 'N/A', 'BELA' => 'N/A',
              'SNC' => 'N/A', 'BSD' => 'N/A', 'CURE' => 'N/A', 'SMART' => 'N/A', 'SNRG' => 'N/A',
              'NVST' => 'N/A', 'XC' => 'N/A', 'ABY' => 'N/A', 'GCR' => 'N/A', 'AUR' => 'N/A',
              'CVCOIN' => 'N/A', 'COVAL' => 'N/A', 'SIGT' => 'N/A', 'QRK' => 'N/A',
              'PASC' => 'N/A', 'BLITZ' => 'N/A', 'XVC' => 'N/A', 'GRE' => 'N/A',
              'ZCL' => 'N/A', 'ZRC' => 'N/A', 'BITB' => 'N/A', 'MNE' => 'N/A', 'SWIFT' => 'N/A',
              'DAXX' => 'N/A', 'MEC' => 'N/A', 'DAR' => 'N/A', 'GLD' => 'N/A',
              'CADASTRAL' => 'N/A', 'RAIN' => 'N/A', 'MAX' => 'N/A', 'HTML5' => 'N/A',
              'ATCC' => 'N/A', 'GEO' => 'N/A', 'ICOO' => 'N/A', 'WBB' => 'N/A', 'XST' => 'N/A',
              'ETT' => 'N/A', 'SPRTS' => 'N/A', 'DYN' => 'N/A', 'ERC' => 'N/A', 'ESP' => 'N/A',
              'KORE' => 'N/A', 'TIPS' => 'N/A', 'DIME' => 'N/A', 'BRX' => 'N/A', 'XCN' => 'N/A',
              'ZENI' => 'N/A', 'VISIO' => 'N/A', 'ZET' => 'N/A',
              'BITUSD' => 'N/A', 'BTA' => 'N/A', 'LGD' => 'N/A',
              'XMY' => 'N/A', 'CHC' => 'N/A', 'SBD' => 'N/A', 'RIC' => 'N/A',
              'COE' => 'N/A', 'LNK' => 'N/A', 'EQT' => 'N/A', 'ZCC' => 'N/A', 'BRK' => 'N/A', 'VRM' => 'N/A',
              'CMP' => 'N/A', 'SKIN' => 'N/A', 'DCN' => 'N/A', 'DOPE' => 'N/A', 'TX' => 'N/A',
              'SYNX' => 'N/A', 'NAUT' => 'N/A', 'FYN' => 'N/A', 'NTRN' => 'N/A', '2GIVE' => 'N/A',
              'STA' => 'N/A', 'VSM' => 'N/A', 'MEME' => 'N/A', 'PTC' => 'N/A', 'CRAVE' => 'N/A',
              'ADZ' => 'N/A', 'EGC' => 'N/A', 'THC' => 'N/A', 'TRC' => 'N/A', 'ARC' => 'N/A',
              'ATMS' => 'N/A', 'PIE' => 'N/A', 'INPAY' => 'N/A', 'CREA' => 'N/A', 'XBB' => 'N/A',
              'MINT' => 'N/A', 'TKS' => 'N/A', 'ZEIT' => 'N/A', 'CV2' => 'N/A', 'VTR' => 'N/A',
              'XWC' => 'N/A', 'CANN' => 'N/A', 'POSW' => 'N/A', '1337' => 'N/A', 'ALT' => 'N/A',
              'LINDA' => 'N/A', 'HUC' => 'N/A', 'TAG' => 'N/A', 'ADST' => 'N/A', 'INSN' => 'N/A',
              'HUSH' => 'N/A', 'DOT' => 'N/A', 'START' => 'N/A', 'EFL' => 'N/A', 'PING' => 'N/A',
              'MER' => 'N/A', 'BLOCKPAY' => 'N/A', 'PKB' => 'N/A', 'CNT' => 'N/A', 'JNS' => 'N/A',
              'TRUST' => 'N/A', 'XMG' => 'N/A', 'FNC' => 'N/A', 'BUN' => 'N/A', 'SMLY' => 'N/A',
              'CAGE' => 'N/A', 'CCRB' => 'N/A', 'RIYA' => 'N/A', 'FST' => 'N/A', 'ENT' => 'N/A',
              'XTO' => 'N/A', 'BTX' => 'N/A', 'ADC' => 'N/A', 'DRACO' => 'N/A', 'HYP' => 'N/A',
              'PND' => 'N/A', 'HNC' => 'N/A', 'LDOGE' => 'N/A', 'BLU' => 'N/A', '808' => 'N/A',
              'ADL' => 'N/A', 'MALC' => 'N/A', 'SXC' => 'N/A', 'RNS' => 'N/A', 'CRM' => 'N/A', 'BYC' => 'N/A',
              'LOG' => 'N/A', 'FIMK' => 'N/A', 'IFLT' => 'N/A', 'BAS' => 'N/A',
              'FUCK' => 'N/A', 'NETKO' => 'N/A', 'CPC' => 'N/A', 'INFX' => 'N/A', 'RBX' => 'N/A',
              'BRO' => 'N/A', 'MRT' => 'N/A', 'XTC' => 'N/A', 'RUSTBITS' => 'N/A', 'UIS' => 'N/A',
              'NKA' => 'N/A', 'HPC' => 'N/A', 'OTX' => 'N/A', 'FCN' => 'N/A', 'ADK' => 'N/A',
              'MBI' => 'N/A', 'LINX' => 'N/A', 'MOIN' => 'N/A', 'FUNC' => 'N/A', 'PROC' => 'N/A',
              'WGO' => 'N/A', 'HKG' => 'N/A', 'HERO' => 'N/A', 'UFO' => 'N/A', 'XP' => 'N/A',
              'ICE' => 'N/A', 'ECA' => 'N/A', 'UNB' => 'N/A', 'XVP' => 'N/A', 'VUC' => 'N/A', 'DCY' => 'N/A',
              'FJC' => 'N/A', 'POST' => 'N/A', 'KEK' => 'N/A', 'XCXT' => 'N/A', 'USNBT' => 'N/A',
              'CFT' => 'N/A', 'PXC' => 'N/A', 'KRB' => 'N/A', 'UNIFY' => 'N/A', 'ITI' => 'N/A',
              'XVS' => 'N/A', 'PAK' => 'N/A', 'DP' => 'N/A', '42' => 'N/A', 'DNR' => 'N/A', 'RBIES' => 'N/A',
              '8BIT' => 'N/A', 'VLT' => 'N/A', 'ZOI' => 'N/A', 'NEWB' => 'N/A', 'DSH' => 'N/A',
              'DEM' => 'N/A', 'TRUMP' => 'N/A', 'CACH' => 'N/A', 'UTC' => 'N/A', 'EL' => 'N/A',
              'HODL' => 'N/A', 'CON' => 'N/A', 'V' => 'N/A', 'ATOM' => 'N/A', 'ZUR' => 'N/A', 'DAS' => 'N/A',
              'CMPCO' => 'N/A',
              'SUMO' => 'N/A', 'MZC' => 'N/A', 'BITS' => 'N/A', 'ZER' => 'N/A', 'CNC' => 'N/A',
              'BITBTC' => 'N/A', 'BUCKS' => 'N/A', 'FXE' => 'N/A', 'YOC' => 'N/A', 'FRN' => 'N/A',
              'XCT' => 'N/A', 'EMD' => 'N/A', 'XHI' => 'N/A', 'LANA' => 'N/A', 'OHM' => 'N/A',
              '4CHN' => 'N/A', 'VIDZ' => 'N/A',
              'MOJO' => 'N/A', 'QCN' => 'N/A', 'BITSILVER' => 'N/A', 'DGC' => 'N/A', 'BLAS' => 'N/A',
              'GCC' => 'N/A', 'UNITS' => 'N/A', 'RUPX' => 'N/A', 'MAO' => 'N/A', 'BTWTY' => 'N/A',
              'CJ' => 'N/A', 'SRC' => 'N/A', 'CORG' => 'N/A', 'BITEUR' => 'N/A', 'KAYI' => 'N/A',
              'SOJ' => 'N/A', 'XLR' => 'N/A',
              'MSCN' => 'N/A', 'EVIL' => 'N/A', 'VTA' => 'N/A', 'FLAX' => 'N/A', 'SCORE' => 'N/A',
              'PRC' => 'N/A', '$$$' => 'N/A', 'TSE' => 'N/A', 'ICOB' => 'N/A', 'MAR' => 'N/A',
              'KURT' => 'N/A', 'GLT' => 'N/A', 'RUP' => 'N/A', 'KLC' => 'N/A', 'BBP' => 'N/A',
              '300' => 'N/A', 'CREVA' => 'N/A', 'UET' => 'N/A',
              'DALC' => 'N/A', 'BOAT' => 'N/A', 'MEOW' => 'N/A', 'IOU' => 'N/A', 'SLEVIN' => 'N/A',
              'ERY' => 'N/A', 'VEC2' => 'N/A', 'CXT' => 'N/A', 'SOCC' => 'N/A', '420G' => 'N/A',
              'ONX' => 'N/A', 'FRAZ' => 'N/A', 'DOLLAR' => 'N/A', 'ACP' => 'N/A', 'PULSE' => 'N/A',
              'ECO' => 'N/A', 'NRO' => 'N/A', 'CTIC2' => 'N/A',
              'LBTC' => 'N/A', 'VRS' => 'N/A', 'QBK' => 'N/A', 'XRC' => 'N/A', 'WEX' => 'N/A',
              'BRIA' => 'N/A', 'LVPS' => 'N/A', 'EBT' => 'N/A', 'APW' => 'N/A', 'ABN' => 'N/A',
              'HMC' => 'N/A', 'ULA' => 'N/A', 'XNG' => 'N/A', 'B@' => 'N/A', 'JINN' => 'N/A',
              'BPC' => 'N/A', 'AC' => 'N/A', 'NSR' => 'N/A', 'STCN' => 'N/A', 'GCN' => 'N/A',
              'IXC' => 'N/A', 'PANGEA' => 'N/A', 'YASH' => 'N/A', 'CARBON' => 'N/A', 'MXT' => 'N/A',
              'CSC' => 'N/A', 'LTBC' => 'N/A', 'HTC' => 'N/A', 'CNO' => 'N/A', 'SDC' => 'N/A',
              'E4ROW' => 'N/A', 'GLC' => 'N/A', 'CASINO' => 'N/A', 'CBX' => 'N/A', 'ORB' => 'N/A',
              'TES' => 'N/A', 'RAREPEPEP' => 'N/A', 'CDN' => 'N/A', 'GOOD' => 'N/A',
              'USC' => 'N/A', 'KOBO' => 'N/A', 'METAL' => 'N/A', 'SHDW' => 'N/A', 'BITZ' => 'N/A',
              'DVC' => 'N/A', 'NOBL' => 'N/A', 'TALK' => 'N/A', 'BTB' => 'N/A', 'I0C' => 'N/A',
              'SHORTY' => 'N/A', 'BTSR' => 'N/A', 'BRIT' => 'N/A', 'STS' => 'N/A', 'MAC' => 'N/A',
              'CRYPT' => 'N/A', 'ANC' => 'N/A', 'SUPER' => 'N/A', 'RLT' => 'N/A', 'HBN' => 'N/A',
              'BTD' => 'N/A', 'TROLL' => 'N/A', 'PIGGY' => 'N/A', 'UNIT' => 'N/A', 'RC' => 'N/A',
              'GAIA' => 'N/A', 'CCN' => 'N/A', 'Q2C' => 'N/A', 'REE' => 'N/A', 'AMBER' => 'N/A',
              'TRK' => 'N/A', 'NYC' => 'N/A', 'TRI' => 'N/A', 'SMC' => 'N/A', 'SLM' => 'N/A', 'FLY' => 'N/A',
              'AU' => 'N/A', 'BXT' => 'N/A', 'FC2' => 'N/A', 'DUO' => 'N/A', 'TIT' => 'N/A', 'FLT' => 'N/A',
              'CAP' => 'N/A', 'GB' => 'N/A', 'KED' => 'N/A', 'XJO' => 'N/A', 'LOT' => 'N/A', 'FRC' => 'N/A',
              'TEK' => 'N/A', 'MNM' => 'N/A', '020' => 'N/A', 'PSB' => 'N/A', 'CHESS' => 'N/A',
              'UNIC' => 'N/A', 'XRA' => 'N/A', 'XPY' => 'N/A', 'ELE' => 'N/A', 'BTCS' => 'N/A',
              'GTC' => 'N/A', 'TTC' => 'N/A', 'JIN' => 'N/A', 'PASL' => 'N/A', 'BSTY' => 'N/A',
              'VAL' => 'N/A', '888' => 'N/A',
              'UNIBURST' => 'N/A', 'TME' => 'N/A', 'WAY' => 'N/A', 'XGR' => 'N/A', 'YAC' => 'N/A',
              'EUC' => 'N/A', 'PIP' => 'N/A', 'C2' => 'N/A', 'KIC' => 'N/A', 'BLC' => 'N/A',
              'CNNC' => 'N/A', 'TGC' => 'N/A', 'SWING' => 'N/A', 'XPD' => 'N/A', 'BOST' => 'N/A',
              'FUNK' => 'N/A', 'SPEX' => 'N/A', 'B3' => 'N/A', 'PXI' => 'N/A', 'MTM' => 'N/A',
              'J' => 'N/A', 'BITGOLD' => 'N/A', 'HMP' => 'N/A',
              'MCRN' => 'N/A', 'WMC' => 'N/A', 'NYAN' => 'N/A', 'UNI' => 'N/A', 'STV' => 'N/A',
              'CYP' => 'N/A', 'JET' => 'N/A', 'BERN' => 'N/A', 'XPTX' => 'N/A', 'LTB' => 'N/A',
              'KUSH' => 'N/A', 'BTCR' => 'N/A', 'RED' => 'N/A', 'CUBE' => 'N/A', 'DRM' => 'N/A',
              'GRT' => 'N/A', 'BOLI' => 'N/A', 'PR' => 'N/A', 'SLG' => 'N/A', 'CRX' => 'N/A',
              'DIBC' => 'N/A', 'MARS' => 'N/A', 'ARI' => 'N/A', 'ARCO' => 'N/A',
              'XRE' => 'N/A', 'ACOIN' => 'N/A', 'XBTC21' => 'N/A', 'HONEY' => 'N/A', 'MAD' => 'N/A',
              'PX' => 'N/A', 'ADCN' => 'N/A', 'SPACE' => 'N/A', 'SOIL' => 'N/A', 'DLC' => 'N/A',
              'ASAFE2' => 'N/A', 'XCO' => 'N/A', 'BIGUP' => 'N/A', 'PHS' => 'N/A', 'WORM' => 'N/A',
              'GUN' => 'N/A', 'SCRT' => 'N/A', 'GPU' => 'N/A', 'VC' => 'N/A', 'SLING' => 'N/A',
              'ARG' => 'N/A', 'GPL' => 'N/A', 'BTPL' => 'N/A', 'BCF' => 'N/A',
              'RBT' => 'N/A', 'ALL' => 'N/A', 'ZNY' => 'N/A', 'ISL' => 'N/A', 'MI' => 'N/A', 'GAP' => 'N/A',
              'TOR' => 'N/A', 'QTL' => 'N/A', 'SPT' => 'N/A', 'BLRY' => 'N/A', 'AUM' => 'N/A',
              'BIP' => 'N/A', 'EVO' => 'N/A', 'BTQ' => 'N/A', 'PONZI' => 'N/A', 'WYV' => 'N/A',
              'CPN' => 'N/A', 'BUMBA' => 'N/A', 'PHO' => 'N/A', 'IMS' => 'N/A', 'HAL' => 'N/A',
              'FRK' => 'N/A', 'BSTAR' => 'N/A', 'DBTC' => 'N/A', 'NEVA' => 'N/A',
              'PUTIC' => 'N/A', 'ZMC' => 'N/A', '611' => 'N/A', 'XCRE' => 'N/A', 'AMMO' => 'N/A',
              'ARB' => 'N/A', 'ANTI' => 'N/A', 'ATX' => 'N/A', 'GBC' => 'N/A', 'POP' => 'N/A',
              'G3N' => 'N/A', 'HXX' => 'N/A', 'GP' => 'N/A', 'U' => 'N/A', 'DRS' => 'N/A',
              'URO' => 'N/A', 'RPC' => 'N/A', 'BNX' => 'N/A', 'BIOS' => 'N/A', 'MST' => 'N/A',
              'BQC' => 'N/A', 'BVC' => 'N/A', 'COAL' => 'N/A', 'CHAO' => 'N/A', 'CAB' => 'N/A',
              'SOON' => 'N/A',
              'SONG' => 'N/A', 'FIRE' => 'N/A', 'LEA' => 'N/A', 'PLNC' => 'N/A', 'CESC' => 'N/A',
              'DIX' => 'N/A', 'MND' => 'N/A', 'STEPS' => 'N/A', 'VIP' => 'N/A', 'JWL' => 'N/A',
              'RIDE' => 'N/A', 'GBT' => 'N/A', 'MTLMC3' => 'N/A', 'HIRO' => 'N/A', 'FLVR' => 'N/A',
              'ICON' => 'N/A', 'MAY' => 'N/A', 'ZYD' => 'N/A', 'VPRC' => 'N/A', 'CWXT' => 'N/A',
              'URC' => 'N/A', 'OFF' => 'N/A', 'TAGR' => 'N/A', 'TSTR' => 'N/A', 'BENJI' => 'N/A',
              'LUNA' => 'N/A', 'MILO' => 'N/A', 'SFC' => 'N/A', 'DES' => 'N/A', 'IBANK' => 'N/A',
              'IMX' => 'N/A', 'CMT' => 'N/A', 'TAJ' => 'N/A', 'DLISK' => 'N/A', 'ORLY' => 'N/A',
              'XBTS' => 'N/A', 'VLTC' => 'N/A', 'AGLC' => 'N/A', 'CTO' => 'N/A', 'HVCO' => 'N/A',
              'FUZZ' => 'N/A', 'WARP' => 'N/A', 'TRADE2' => 'N/A', 'OS76' => 'N/A', 'BLZ' => 'N/A',
              'EGO' => 'N/A', 'SCS' => 'N/A', 'DPAY' => 'N/A', 'KNC' => 'N/A', 'PRX' => 'N/A', 'BSC' => 'N/A',
              'CASH' => 'N/A', 'IMPS' => 'N/A', 'XOC' => 'N/A', 'CRT' => 'N/A', 'PEX' => 'N/A',
              'MNC' => 'N/A', 'REV' => 'N/A', 'LTCR' => 'N/A', 'LIR' => 'N/A', 'ZNE' => 'N/A',
              'RSGP' => 'N/A', 'CONX' => 'N/A', 'SH' => 'N/A', 'CCM100' => 'N/A', 'JOBS' => 'N/A',
              'ALTC' => 'N/A', 'SANDG' => 'N/A', '1CR' => 'N/A', 'SDP' => 'N/A', 'ARGUS' => 'N/A',
              'GEERT' => 'N/A', 'JIO' => 'N/A', 'VOLT' => 'N/A', 'OCEAN' => 'N/A', 'MGM' => 'N/A',
              'BIOB' => 'N/A',
              'P7C' => 'N/A', 'NODC' => 'N/A', 'CF' => 'N/A', 'SLFI' => 'N/A', 'LEX' => 'N/A',
              'ELS' => 'N/A', 'ENV' => 'N/A', 'PIZZA' => 'N/A', 'FDC' => 'N/A', 'DRAGON' => 'N/A',
              'PWR' => 'N/A', 'TOKEN' => 'N/A', 'ETB' => 'N/A', 'DGCS' => 'N/A', 'MUG' => 'N/A',
              'DMB' => 'N/A', 'XEN' => 'N/A', 'CALC' => 'N/A', 'FEDS' => 'N/A', 'GXS' => 'N/A',
              'VEN' => 'N/A', 'ACT' => 'N/A', 'WTC' => 'N/A', 'DOC' => 'N/A', 'INF' => 'N/A',
              'HCC' => 'N/A', 'SJCX' => 'N/A', 'PURA' => 'N/A', 'SIGMA' => 'N/A', 'DMC' => 'N/A',
              'NAS' => 'N/A', 'FID' => 'N/A', 'KRS' => 'N/A', 'NAMO' => 'N/A', 'FRGC' => 'N/A',
              'EOT' => 'N/A', 'EBST' => 'N/A', 'HLB' => 'N/A', 'XID' => 'N/A', 'ABC' => 'N/A',
              'FAL' => 'N/A', 'GBG' => 'N/A', 'THS' => 'N/A', 'IFT' => 'N/A', 'BGC' => 'N/A',
              'OPT' => 'N/A', 'CTR' => 'N/A', 'DEUS' => 'N/A', 'GYC' => 'N/A', 'GRWI' => 'N/A',
              'FBC' => 'N/A', 'CLUB' => 'N/A', 'YOYOW' => 'N/A', 'IOP' => 'N/A', 'AE' => 'N/A',
              'ASN' => 'N/A', 'ELC' => 'N/A', 'BDL' => 'N/A', 'BITCF' => 'N/A', 'MKR' => 'N/A',
              'DTF' => 'N/A', 'BRAT' => 'N/A', 'ZBC' => 'N/A', 'BTU' => 'N/A', 'DHG' => 'N/A',
              'DDF' => 'N/A', 'WA' => 'N/A', 'XTD' => 'N/A', 'BQ' => 'N/A', 'PCS' => 'N/A',
              'AURS' => 'N/A', 'TYCHO' => 'N/A', 'TER' => 'N/A', 'XMCC' => 'N/A', 'FEI' => 'N/A',
              'EMP' => 'N/A', 'FLASH' => 'N/A', 'AXF' => 'N/A', 'BLN' => 'N/A', 'MG' => 'N/A',
              'PRN' => 'N/A', 'USDE' => 'N/A', 'OX' => 'N/A', 'BITOK' => 'N/A', 'ACC' => 'N/A',
              'UR' => 'N/A', 'HALLO' => 'N/A', 'HBC' => 'N/A', 'PAC' => 'N/A', 'TCOIN' => 'N/A',
              'WEC' => 'N/A', 'APC' => 'N/A', 'DBG' => 'N/A', 'WOMEN' => 'N/A', 'XOT' => 'N/A',
              'AMIS' => 'N/A', 'TERA' => 'N/A', 'TESLA' => 'N/A', 'LDCN' => 'N/A', 'BIRDS' => 'N/A',
              'GARY' => 'N/A', 'EDRC' => 'N/A', '9COIN' => 'N/A', 'STEX' => 'N/A', 'PRES' => 'N/A',
              'SMOKE' => 'N/A', 'NXX' => 'N/A', 'RMC' => 'N/A', 'SHND' => 'N/A', 'YES' => 'N/A',
              'CYC' => 'N/A', 'EXL' => 'N/A', 'ANI' => 'N/A', 'AMS' => 'N/A', 'SKULL' => 'N/A',
              'COUPE' => 'N/A', 'TYC' => 'N/A', 'ACES' => 'N/A', 'SNAKE' => 'N/A', 'GAY' => 'N/A',
              'SYNC' => 'N/A', 'XLC' => 'N/A', 'AV' => 'N/A', 'XQN' => 'N/A', 'MEN' => 'N/A', 'ACN' => 'N/A',
              'OPAL' => 'N/A', 'TOPAZ' => 'N/A', 'YOG' => 'N/A', 'BXC' => 'N/A', 'PRIMU' => 'N/A',
              'SAK' => 'N/A', 'CLINT' => 'N/A', 'RUBIT' => 'N/A', 'RBBT' => 'N/A', 'UTA' => 'N/A',
              'ATMC' => 'N/A', 'DON' => 'N/A', 'PDG' => 'N/A', 'FAZZ' => 'N/A', 'SKR' => 'N/A',
              'BIT' => 'N/A', 'NBE' => 'N/A', 'NANOX' => 'N/A', 'VOYA' => 'N/A', 'CC' => 'N/A',
              'LKC' => 'N/A', 'IRL' => 'N/A', 'MINEX' => 'N/A', 'WINK' => 'N/A', 'EFYT' => 'N/A',
              'MARX' => 'N/A', 'BRAIN' => 'N/A', 'SHA' => 'N/A', 'ETX' => 'N/A', 'SFE' => 'N/A',
              'PCN' => 'N/A', 'QORA' => 'N/A', 'PEC' => 'N/A', 'FFC' => 'N/A', 'BTG' => 'N/A',
              'TOP' => 'N/A', 'UNRC' => 'N/A', 'NTCC' => 'N/A', 'XBG' => 'N/A', 'SKC' => 'N/A',
              'MIU' => 'N/A', 'GSR' => 'N/A', 'LEPEN' => 'N/A', 'VGC' => 'N/A', 'KASHH' => 'N/A',
              'AXIOM' => 'N/A', 'FONZ' => 'N/A', 'ANTX' => 'N/A', 'GUC' => 'N/A', 'MONEY' => 'N/A',
              'BLAZR' => 'N/A', 'DISK' => 'N/A', 'PI' => 'N/A', 'MOTO' => 'N/A', 'DASHS' => 'N/A',
              'FRWC' => 'N/A',
              'TELL' => 'N/A', 'RHFC' => 'N/A', 'TLE' => 'N/A', 'XRY' => 'N/A', 'QBC' => 'N/A',
              'ZSE' => 'N/A', 'AIB' => 'N/A', 'BEST' => 'N/A', 'GBRC' => 'N/A', 'KARMA' => 'N/A',
              'FUTC' => 'N/A', 'QBT' => 'N/A', 'DUB' => 'N/A', 'TODAY' => 'N/A', 'VTY' => 'N/A',
              'ZENGOLD' => 'N/A', 'SPORT' => 'N/A', 'XVE' => 'N/A', 'MAVRO' => 'N/A', 'ROYAL' => 'N/A',
              'HILL' => 'N/A', 'XSTC' => 'N/A', 'CHEAP' => 'N/A', 'UNC' => 'N/A', 'LTH' => 'N/A',
              'MONETA' => 'N/A', 'DFT' => 'N/A', 'OP' => 'N/A', 'SOUL' => 'N/A', 'REGA' => 'N/A',
              'X2' => 'N/A', 'WSX' => 'N/A', 'CBD' => 'N/A', 'HYPER' => 'N/A', 'POKE' => 'N/A',
              'OCOW' => 'N/A', 'PAYP' => 'N/A', 'BGR' => 'N/A', 'TCR' => 'N/A', 'GMB' => 'N/A',
              'GML' => 'N/A', 'SHELL' => 'N/A', 'GAIN' => 'N/A', 'TEAM' => 'N/A', 'BAC' => 'N/A',
              'OPES' => 'N/A', 'LAZ' => 'N/A', 'MMXVI' => 'N/A', 'PRM' => 'N/A', 'CME' => 'N/A',
              'XDE2' => 'N/A', 'XAU' => 'N/A', 'NBIT' => 'N/A', 'RCN' => 'N/A', 'WOW' => 'N/A',
              'OMC' => 'N/A', 'DCRE' => 'N/A', 'BURN' => 'N/A', 'TURBO' => 'N/A', 'EGG' => 'N/A',
              'RYCN' => 'N/A', 'TRICK' => 'N/A', 'QRZ' => 'N/A', 'COXST' => 'N/A', 'MRC' => 'N/A',
              'IVZ' => 'N/A', 'STRB' => 'N/A', 'PSY' => 'N/A', 'TP1' => 'N/A', 'RICHX' => 'N/A',
              'ASC' => 'N/A', 'MBL' => 'N/A', 'GOLF' => 'N/A', 'GMX' => 'N/A'
  }

  print GITHUB_MAP.values.count {|x| x != ('N/A')}

end

# Assets with more than one github organization:
# BCH

# Assets with a github organization that needs reduced repos (due to working on unrelated projects):
# OMG, KMD, NXT, MCAP, PLR, VSL, EB3, XRB, XBY, VOX

# Primarily private repos
# PAY, BCAP

# Appears to be a personal github account
# BCN, KMD, NXT, BTCD, VSL, EB3, SOAR, ClAM, RADS, SIB, XRB, XBY, GAM

# Can't find Github organization
# MCO, BNB, CVC, ARDR, FUN, MGO, ICO, BQX, ROUND, XRL, TAAS, TCC, DICE, IXT, PLBT, NXC, DTB, AGRS, QAU, ECOB, BET, OBITS, BITCNY, INCNT, UNY, DENT, PEPECASH, EMV

# Closed Source
# ICN, FUN, PLR, PTOY(probably)

# Organizations responsible for > 1 token
# neo-project: NEO & GAS
# supernet/komodo: KMD & UNITY (not sure of relationship - investigate )
# Waves: WCT & WAVES
